[package]
name = "bitcoin_hd"
version = "0.6.0-rc.3"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Bitcoin hierarchical deterministic wallet library"
repository = "https://github.com/LNP-BP/descriptor-wallet"
homepage = "https://github.com/LNP-BP/descriptor-wallet/tree/master/bitcoin_hd"
keywords = ["bitcoin", "wallet", "cryptocurrency", "cryptography", "bip32"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "../README.md"
edition = "2018"
exclude = []

[dependencies]
amplify = "3.12.0"
strict_encoding = "1.8.0-rc.7"
bitcoin = "0.28.0-rc.2"
miniscript = { version = "7.0.0-rc.2", optional = true }
slip132 = { version = "0.6.0-rc.2", path = "../slip132" }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.5", features = ["hex"], optional = true }

[features]
default = []
all = ["serde", "miniscript"]
serde = ["serde_crate", "serde_with", "amplify/serde", "bitcoin/serde", "slip132/serde"]
