[package]
name = "bitcoin_onchain"
version = "0.6.0-rc.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Bitcoin descriptors library (part of descriptor-wallet)"
repository = "https://github.com/LNP-BP/descriptor-wallet"
homepage = "https://github.com/LNP-BP/descriptor-wallet/tree/master/descriptors"
keywords = ["bitcoin", "wallet", "cryptocurrency", "descriptor", "bip32"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "../README.md"
edition = "2018"
exclude = []

[dependencies]
amplify = "3.12.0"
bitcoin = "0.28.0-rc.2"
strict_encoding = "1.8.0-rc.7"
descriptors = { version = "0.6.0-rc.1", path = "../descriptors", default-features = false }
bitcoin_hd = { version = "0.6.0-rc.1", path = "../hd" }
miniscript_crate = { package = "miniscript", version = "7.0.0-rc.2", optional = true }
electrum-client = { version = "=0.9.0-rc.1", optional = true }
chrono = "0.4.19"

[features]
default = []
all = ["electrum", "miniscript"]
miniscript = ["miniscript_crate", "descriptors/miniscript", "bitcoin_hd/miniscript"]
electrum = ["electrum-client"]
