[package]
name = "psbt"
version = "0.6.0-rc.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Partially signed bitcoin transaction v0-2 library (bip174, bip370, bip371)"
repository = "https://github.com/LNP-BP/descriptor-wallet"
homepage = "https://github.com/LNP-BP/descriptor-wallet/tree/master/psbt"
keywords = ["bitcoin", "wallet", "cryptocurrency", "psbt", "taproot"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "../README.md"
edition = "2018"
exclude = []

[dependencies]
amplify = "3.12.0"
bitcoin = { version = "0.28.0-rc.2", features = ["base64"] }
miniscript_crate = { package = "miniscript", version = "7.0.0-rc.2", optional = true }
descriptors = { version = "0.6.0-rc.1", path = "../descriptors", default-features = false }
bitcoin_scripts = { version = "0.6.0-rc.1", path = "../scripts" }
bitcoin_hd = { version = "0.6.0-rc.1", path = "../hd" }
bitcoin_onchain = { version = "0.6.0-rc.1", path = "../onchain" }

[features]
default = ["miniscript"]
all = ["sign", "miniscript"]
miniscript = ["miniscript_crate", "descriptors/miniscript", "bitcoin_scripts/miniscript", "bitcoin_onchain/miniscript"]
sign = ["bitcoin/rand"]
