[package]
name = "bitcoin_scripts"
version = "0.6.0-rc.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Bitcoin extended script types"
repository = "https://github.com/LNP-BP/descriptor-wallet"
homepage = "https://github.com/LNP-BP/descriptor-wallet/tree/master/scripts"
keywords = ["bitcoin", "wallet", "cryptocurrency", "cryptography", "bitcoin-script"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "../README.md"
edition = "2018"
exclude = []

[dependencies]
amplify = "3.12.0"
bitcoin = "0.28.0-rc.2"
miniscript = { version = "7.0.0-rc.2", optional = true }
strict_encoding = "1.8.0-rc.7"
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.8", optional = true }

[dev-dependencies]
secp256k1 = { version = "0.21.2", features = ["global-context"] }

[features]
default = []
all = ["serde", "miniscript"]
serde = ["serde_crate", "serde_with", "amplify/serde", "bitcoin/use-serde"]
