name: Tests

on:
  push:
    branches: [ master, 'v*' ]
  pull_request:
    branches: [ master, 'v*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Test main lib
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features --all-targets --no-fail-fast
      - name: Test slip132
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path slip132/Cargo.toml --all-features --no-fail-fast
  testing-c-lang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Test c bindings
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path libbitcoin/Cargo.toml --all-features --no-fail-fast
